language: php
php:
  - 7.4
dist: focal
env:
  matrix:
    - MAGENTO_VERSION=2.3.7 TEST_SUITE=unit
    - MAGENTO_VERSION=2.3.7 TEST_SUITE=static
cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.nvm"
install:
  - echo "$AUTH" > auth.json
  - composer install --no-interaction --prefer-dist
script:
  - if [ $TEST_SUITE == "unit" ]; then ./vendor/bin/phpunit; fi
  - if [ $TEST_SUITE == "static" ]; then ./vendor/bin/phpcs; fi

